# -*- coding: utf-8 -*-
"""Latihan1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tK5K5GmFVgskz55ZIfcRWqKyLkjnA0PP
"""

pip install tensorflow numpy matplotlib scikit-learn pydot graphviz

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

# Latihan 1: CNN dari Scratch untuk CIFAR-10
def praktikum_cnn_from_scratch():
    print("LATIHAN 1: CNN DARI AWAL UNTUK CIFAR-10")
    print("=" * 50)

    # Load CIFAR-10 dataset
    (X_train, y_train), (X_test, y_test) = keras.datasets.cifar10.load_data()

    print(f"Training data shape: {X_train.shape}")
    print(f"Test data shape: {X_test.shape}")

    # Normalize pixel values to [0, 1]
    X_train = X_train.astype('float32') / 255.0
    X_test = X_test.astype('float32') / 255.0

    # One-hot encode labels
    num_classes = 10
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    # Visualize sample images
    class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
                   'dog', 'frog', 'horse', 'ship', 'truck']

    plt.figure(figsize=(10, 10))
    for i in range(25):
        plt.subplot(5, 5, i + 1)
        plt.imshow(X_train[i])
        plt.title(class_names[np.argmax(y_train[i])])
        plt.axis('off')
    plt.suptitle("Sample Images from CIFAR-10", fontsize=16)
    plt.tight_layout()
    plt.show()

    # Build CNN from scratch
    def build_cnn_model(input_shape=(32, 32, 3), num_classes=10):
        model = keras.Sequential([
            layers.Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=input_shape, name='conv1'),
            layers.BatchNormalization(name='bn1'),
            layers.Conv2D(32, (3, 3), padding='same', activation='relu', name='conv2'),
            layers.BatchNormalization(name='bn2'),
            layers.MaxPooling2D((2, 2), name='pool1'),
            layers.Dropout(0.25, name='dropout1'),

            layers.Conv2D(64, (3, 3), padding='same', activation='relu', name='conv3'),
            layers.BatchNormalization(name='bn3'),
            layers.Conv2D(64, (3, 3), padding='same', activation='relu', name='conv4'),
            layers.BatchNormalization(name='bn4'),
            layers.MaxPooling2D((2, 2), name='pool2'),
            layers.Dropout(0.25, name='dropout2'),

            layers.Flatten(name='flatten'),
            layers.Dense(256, activation='relu', name='fc1'),
            layers.BatchNormalization(name='bn7'),
            layers.Dropout(0.5, name='dropout4'),
            layers.Dense(num_classes, activation='softmax', name='output')
        ])
        return model

    # Create model
    model = build_cnn_model()

    # Display model architecture
    print("\nCNN MODEL ARCHITECTURE:")
    print("=" * 40)
    model.summary()

    # Install graphviz system library and plot
    !apt-get install -y graphviz libgraphviz-dev
    keras.utils.plot_model(model, to_file='model_architecture.png', show_shapes=True)

    # Display the plot
    from IPython.display import Image, display
    display(Image(filename='model_architecture.png'))

    # Compile and Train
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    print("\nTRAINING MODEL...")
    history = model.fit(X_train, y_train, batch_size=64, epochs=5, validation_split=0.2, verbose=1)

    return model, history

# Run training
model, history = praktikum_cnn_from_scratch()